"""Notification

Revision ID: 2c344a79c26b
Revises: d5e0be332807
Create Date: 2020-12-09 13:36:07.266579

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2c344a79c26b'
down_revision = 'd5e0be332807'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('expo_token', sa.String(length=123), nullable=True))
    op.add_column('users', sa.Column('notification_enabled', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'notification_enabled')
    op.drop_column('users', 'expo_token')
    # ### end Alembic commands ###
