import os

BEACON_URI = os.environ['BEACON_URI']
BEACON_RPC_URI = f'{BEACON_URI}/eth/v1alpha1'
# EPOCH_GENESIS = 1606824023 # Mainnet
EPOCH_GENESIS = 1605700800  # Pyrmont
SEC_PER_SLOT = 12
SLOTS_PER_EPOCH = 32
SEC_PER_EPOCH = SEC_PER_SLOT * SLOTS_PER_EPOCH
SEC_PER_DAY = 86400
EPOCH_PER_DAY = int(SEC_PER_DAY / SEC_PER_EPOCH)
